/**
 * 15 plantillas inmobiliarias pre-diseñadas.
 *
 * Cada plantilla devuelve un canvasData (JSON serializable de Fabric) listo
 * para hidratar en el canvas. Los placeholders ({{precio}}, {{specs}}, etc)
 * se reemplazan con `applySmartFill()` en lib/editor/smart-fill.ts.
 *
 * Las plantillas son funciones puras que devuelven JSON simple para Fabric.
 * Las fuentes asumen que ya están cargadas globalmente (Raleway + fallbacks).
 */

export type TemplateCategory = "sale" | "open-house" | "sold" | "price-drop" | "agent" | "carousel";

export type RealEstateTemplate = {
  id: string;
  name: string;
  description: string;
  category: TemplateCategory;
  thumbnail: string; // emoji-based placeholder, real ones come later
  format: "SQUARE" | "STORY" | "LANDSCAPE";
  width: number;
  height: number;
  background: string;
  /** Fabric JSON v6 objects array */
  objects: unknown[];
};

const GREEN = "#00bf63";
const INK = "#0a0a0a";
const WHITE = "#ffffff";
const GOLD = "#facc15";
const RED = "#dc2626";

function textbox(opts: {
  text: string;
  left: number;
  top: number;
  width?: number;
  fontSize: number;
  fontFamily?: string;
  fontWeight?: number;
  fill?: string;
  textAlign?: string;
  letterSpacing?: number;
  angle?: number;
}) {
  return {
    type: "Textbox",
    text: opts.text,
    left: opts.left,
    top: opts.top,
    width: opts.width ?? 600,
    fontSize: opts.fontSize,
    fontFamily: opts.fontFamily ?? "Raleway",
    fontWeight: opts.fontWeight ?? 700,
    fill: opts.fill ?? INK,
    textAlign: opts.textAlign ?? "left",
    charSpacing: (opts.letterSpacing ?? 0) * 100,
    angle: opts.angle ?? 0,
    originX: "left",
    originY: "top",
  };
}

function rect(opts: {
  left: number;
  top: number;
  width: number;
  height: number;
  fill: string;
  rx?: number;
  ry?: number;
  angle?: number;
  shadow?: string;
}) {
  return {
    type: "Rect",
    left: opts.left,
    top: opts.top,
    width: opts.width,
    height: opts.height,
    fill: opts.fill,
    rx: opts.rx ?? 0,
    ry: opts.ry ?? opts.rx ?? 0,
    angle: opts.angle ?? 0,
    shadow: opts.shadow,
    originX: "left",
    originY: "top",
  };
}

function placeholderImage(opts: {
  left: number;
  top: number;
  width: number;
  height: number;
}) {
  return {
    type: "Rect",
    left: opts.left,
    top: opts.top,
    width: opts.width,
    height: opts.height,
    fill: "#1f2937",
    rx: 12,
    ry: 12,
    name: "{{property_photo}}",
    placeholder: true,
    originX: "left",
    originY: "top",
  };
}

export const TEMPLATES: RealEstateTemplate[] = [
  // 1
  {
    id: "sale-tropical",
    name: "En Venta · Tropical",
    description: "Hero con palmera, verde estaila, ideal Caribe.",
    category: "sale",
    thumbnail: "🌴",
    format: "SQUARE",
    width: 1080,
    height: 1080,
    background: WHITE,
    objects: [
      placeholderImage({ left: 60, top: 60, width: 960, height: 600 }),
      rect({ left: 60, top: 680, width: 320, height: 60, fill: GREEN, rx: 8 }),
      textbox({
        text: "EN VENTA",
        left: 80,
        top: 690,
        width: 280,
        fontSize: 32,
        fontWeight: 900,
        fill: WHITE,
        letterSpacing: 4,
      }),
      textbox({
        text: "{{title}}",
        left: 60,
        top: 770,
        width: 960,
        fontSize: 56,
        fontWeight: 800,
        fill: INK,
      }),
      textbox({
        text: "{{specs}}",
        left: 60,
        top: 870,
        width: 600,
        fontSize: 22,
        fontWeight: 500,
        fill: "#525252",
      }),
      textbox({
        text: "{{price}}",
        left: 60,
        top: 920,
        width: 960,
        fontSize: 64,
        fontWeight: 900,
        fill: GREEN,
        fontFamily: "JetBrains Mono",
      }),
      textbox({
        text: "{{agent_name}}  ·  {{agent_phone}}",
        left: 60,
        top: 1010,
        width: 960,
        fontSize: 20,
        fontWeight: 600,
        fill: INK,
      }),
    ],
  },
  // 2
  {
    id: "sale-luxury",
    name: "En Venta · Luxury",
    description: "Negro + dorado sobrio para propiedades premium.",
    category: "sale",
    thumbnail: "💎",
    format: "SQUARE",
    width: 1080,
    height: 1080,
    background: "#0a0a0a",
    objects: [
      placeholderImage({ left: 80, top: 80, width: 920, height: 720 }),
      textbox({
        text: "EXCLUSIVA",
        left: 80,
        top: 830,
        width: 920,
        fontSize: 18,
        fontWeight: 700,
        fill: GOLD,
        letterSpacing: 8,
      }),
      textbox({
        text: "{{title}}",
        left: 80,
        top: 870,
        width: 920,
        fontSize: 52,
        fontWeight: 300,
        fill: WHITE,
        fontFamily: "Playfair Display",
      }),
      textbox({
        text: "{{price}}",
        left: 80,
        top: 960,
        width: 920,
        fontSize: 28,
        fontWeight: 600,
        fill: GOLD,
        fontFamily: "JetBrains Mono",
      }),
    ],
  },
  // 3
  {
    id: "sale-minimal",
    name: "En Venta · Minimalista",
    description: "Espacio en blanco, tipografía clara.",
    category: "sale",
    thumbnail: "⚪",
    format: "SQUARE",
    width: 1080,
    height: 1080,
    background: "#fafafa",
    objects: [
      placeholderImage({ left: 90, top: 90, width: 900, height: 600 }),
      textbox({
        text: "PROPIEDAD EN VENTA",
        left: 90,
        top: 720,
        width: 900,
        fontSize: 16,
        fontWeight: 600,
        fill: "#525252",
        letterSpacing: 4,
      }),
      textbox({
        text: "{{title}}",
        left: 90,
        top: 760,
        width: 900,
        fontSize: 64,
        fontWeight: 700,
        fill: INK,
      }),
      textbox({
        text: "{{price}}",
        left: 90,
        top: 880,
        width: 900,
        fontSize: 36,
        fontWeight: 600,
        fill: GREEN,
        fontFamily: "JetBrains Mono",
      }),
      textbox({
        text: "{{location}}  ·  {{specs}}",
        left: 90,
        top: 950,
        width: 900,
        fontSize: 20,
        fontWeight: 500,
        fill: "#525252",
      }),
    ],
  },
  // 4
  {
    id: "open-house-saturday",
    name: "Open House · Sábado",
    description: "Banner inferior amarillo con fecha grande.",
    category: "open-house",
    thumbnail: "📅",
    format: "SQUARE",
    width: 1080,
    height: 1080,
    background: WHITE,
    objects: [
      placeholderImage({ left: 0, top: 0, width: 1080, height: 720 }),
      rect({ left: 0, top: 720, width: 1080, height: 360, fill: GOLD }),
      textbox({
        text: "OPEN HOUSE",
        left: 60,
        top: 760,
        width: 960,
        fontSize: 28,
        fontWeight: 800,
        fill: INK,
        letterSpacing: 8,
      }),
      textbox({
        text: "{{open_house_date}}",
        left: 60,
        top: 810,
        width: 960,
        fontSize: 96,
        fontWeight: 900,
        fill: INK,
      }),
      textbox({
        text: "{{title}}  ·  {{location}}",
        left: 60,
        top: 960,
        width: 960,
        fontSize: 22,
        fontWeight: 600,
        fill: INK,
      }),
      textbox({
        text: "RSVP {{agent_phone}}",
        left: 60,
        top: 1010,
        width: 960,
        fontSize: 18,
        fontWeight: 500,
        fill: INK,
      }),
    ],
  },
  // 5
  {
    id: "sold-diagonal",
    name: "VENDIDO · Diagonal",
    description: "Banner diagonal verde con testimonio.",
    category: "sold",
    thumbnail: "✅",
    format: "SQUARE",
    width: 1080,
    height: 1080,
    background: WHITE,
    objects: [
      placeholderImage({ left: 60, top: 60, width: 960, height: 960 }),
      rect({
        left: 540,
        top: 540,
        width: 1100,
        height: 140,
        fill: GREEN,
        angle: -20,
      }),
      textbox({
        text: "VENDIDO",
        left: 100,
        top: 480,
        width: 880,
        fontSize: 96,
        fontWeight: 900,
        fill: WHITE,
        letterSpacing: 8,
        angle: -20,
        textAlign: "center",
      }),
    ],
  },
  // 6
  {
    id: "price-drop",
    name: "Precio Reducido",
    description: "Badge llamativo con precio anterior tachado.",
    category: "price-drop",
    thumbnail: "📉",
    format: "SQUARE",
    width: 1080,
    height: 1080,
    background: WHITE,
    objects: [
      placeholderImage({ left: 60, top: 60, width: 960, height: 600 }),
      rect({ left: 60, top: 680, width: 420, height: 80, fill: RED, rx: 12 }),
      textbox({
        text: "PRECIO REDUCIDO",
        left: 75,
        top: 695,
        width: 410,
        fontSize: 30,
        fontWeight: 900,
        fill: WHITE,
        letterSpacing: 4,
      }),
      textbox({
        text: "{{title}}",
        left: 60,
        top: 790,
        width: 960,
        fontSize: 48,
        fontWeight: 800,
        fill: INK,
      }),
      textbox({
        text: "Antes",
        left: 60,
        top: 870,
        width: 200,
        fontSize: 18,
        fontWeight: 500,
        fill: "#525252",
      }),
      textbox({
        text: "{{old_price}}",
        left: 60,
        top: 895,
        width: 380,
        fontSize: 32,
        fontWeight: 600,
        fill: "#999",
        fontFamily: "JetBrains Mono",
      }),
      textbox({
        text: "Ahora",
        left: 480,
        top: 870,
        width: 200,
        fontSize: 18,
        fontWeight: 500,
        fill: GREEN,
      }),
      textbox({
        text: "{{price}}",
        left: 480,
        top: 895,
        width: 540,
        fontSize: 56,
        fontWeight: 900,
        fill: GREEN,
        fontFamily: "JetBrains Mono",
      }),
    ],
  },
  // 7
  {
    id: "story-sale",
    name: "Story · En Venta",
    description: "Vertical IG/WhatsApp con CTA WhatsApp.",
    category: "sale",
    thumbnail: "📱",
    format: "STORY",
    width: 1080,
    height: 1920,
    background: INK,
    objects: [
      placeholderImage({ left: 60, top: 200, width: 960, height: 1200 }),
      textbox({
        text: "EN VENTA",
        left: 60,
        top: 1460,
        width: 960,
        fontSize: 28,
        fontWeight: 800,
        fill: GREEN,
        letterSpacing: 8,
      }),
      textbox({
        text: "{{title}}",
        left: 60,
        top: 1510,
        width: 960,
        fontSize: 72,
        fontWeight: 800,
        fill: WHITE,
      }),
      textbox({
        text: "{{price}}",
        left: 60,
        top: 1660,
        width: 960,
        fontSize: 56,
        fontWeight: 900,
        fill: GREEN,
        fontFamily: "JetBrains Mono",
      }),
      rect({ left: 60, top: 1780, width: 960, height: 90, fill: GREEN, rx: 45 }),
      textbox({
        text: "💬  Chatea por WhatsApp",
        left: 60,
        top: 1800,
        width: 960,
        fontSize: 26,
        fontWeight: 700,
        fill: WHITE,
        textAlign: "center",
      }),
    ],
  },
  // 8
  {
    id: "agent-card",
    name: "Agente · Tarjeta",
    description: "Foto del agente + datos clave + CTA.",
    category: "agent",
    thumbnail: "👤",
    format: "SQUARE",
    width: 1080,
    height: 1080,
    background: INK,
    objects: [
      placeholderImage({ left: 90, top: 90, width: 400, height: 400 }),
      textbox({
        text: "Tu agente inmobiliario",
        left: 540,
        top: 120,
        width: 480,
        fontSize: 18,
        fontWeight: 600,
        fill: GREEN,
        letterSpacing: 4,
      }),
      textbox({
        text: "{{agent_name}}",
        left: 540,
        top: 170,
        width: 480,
        fontSize: 64,
        fontWeight: 800,
        fill: WHITE,
      }),
      textbox({
        text: "{{agent_role}}",
        left: 540,
        top: 310,
        width: 480,
        fontSize: 20,
        fontWeight: 500,
        fill: "#a3a3a3",
      }),
      textbox({
        text: "📞  {{agent_phone}}",
        left: 90,
        top: 580,
        width: 930,
        fontSize: 26,
        fontWeight: 500,
        fill: WHITE,
      }),
      textbox({
        text: "💬  WhatsApp directo",
        left: 90,
        top: 640,
        width: 930,
        fontSize: 26,
        fontWeight: 500,
        fill: WHITE,
      }),
      textbox({
        text: "🌐  {{website}}",
        left: 90,
        top: 700,
        width: 930,
        fontSize: 26,
        fontWeight: 500,
        fill: WHITE,
      }),
    ],
  },
  // 9
  {
    id: "before-after",
    name: "Antes y Después",
    description: "Split vertical para mostrar staging IA.",
    category: "carousel",
    thumbnail: "🪄",
    format: "SQUARE",
    width: 1080,
    height: 1080,
    background: WHITE,
    objects: [
      placeholderImage({ left: 0, top: 0, width: 540, height: 1080 }),
      placeholderImage({ left: 540, top: 0, width: 540, height: 1080 }),
      rect({ left: 40, top: 40, width: 110, height: 36, fill: INK, rx: 18 }),
      textbox({
        text: "ANTES",
        left: 40,
        top: 47,
        width: 110,
        fontSize: 16,
        fontWeight: 800,
        fill: WHITE,
        textAlign: "center",
        letterSpacing: 2,
      }),
      rect({ left: 580, top: 40, width: 140, height: 36, fill: GREEN, rx: 18 }),
      textbox({
        text: "DESPUÉS",
        left: 580,
        top: 47,
        width: 140,
        fontSize: 16,
        fontWeight: 800,
        fill: WHITE,
        textAlign: "center",
        letterSpacing: 2,
      }),
    ],
  },
  // 10
  {
    id: "specs-list",
    name: "Specs detalladas",
    description: "Lista vertical con habitaciones, baños, m².",
    category: "sale",
    thumbnail: "📐",
    format: "SQUARE",
    width: 1080,
    height: 1080,
    background: WHITE,
    objects: [
      placeholderImage({ left: 540, top: 0, width: 540, height: 1080 }),
      textbox({
        text: "{{title}}",
        left: 60,
        top: 100,
        width: 440,
        fontSize: 44,
        fontWeight: 800,
        fill: INK,
      }),
      textbox({
        text: "{{location}}",
        left: 60,
        top: 220,
        width: 440,
        fontSize: 20,
        fontWeight: 500,
        fill: "#525252",
      }),
      textbox({
        text: "🛏️  {{bedrooms}} habitaciones",
        left: 60,
        top: 360,
        width: 440,
        fontSize: 24,
        fontWeight: 600,
        fill: INK,
      }),
      textbox({
        text: "🛁  {{bathrooms}} baños",
        left: 60,
        top: 420,
        width: 440,
        fontSize: 24,
        fontWeight: 600,
        fill: INK,
      }),
      textbox({
        text: "📐  {{area}} m²",
        left: 60,
        top: 480,
        width: 440,
        fontSize: 24,
        fontWeight: 600,
        fill: INK,
      }),
      textbox({
        text: "🚗  {{parking}} estacionamientos",
        left: 60,
        top: 540,
        width: 440,
        fontSize: 24,
        fontWeight: 600,
        fill: INK,
      }),
      textbox({
        text: "{{price}}",
        left: 60,
        top: 720,
        width: 440,
        fontSize: 64,
        fontWeight: 900,
        fill: GREEN,
        fontFamily: "JetBrains Mono",
      }),
      textbox({
        text: "{{agent_name}}",
        left: 60,
        top: 920,
        width: 440,
        fontSize: 20,
        fontWeight: 600,
        fill: INK,
      }),
      textbox({
        text: "{{agent_phone}}",
        left: 60,
        top: 960,
        width: 440,
        fontSize: 18,
        fontWeight: 500,
        fill: "#525252",
      }),
    ],
  },
  // 11
  {
    id: "new-listing",
    name: "Nuevo Listado",
    description: "Badge esquina + foto grande.",
    category: "sale",
    thumbnail: "🆕",
    format: "SQUARE",
    width: 1080,
    height: 1080,
    background: WHITE,
    objects: [
      placeholderImage({ left: 60, top: 60, width: 960, height: 960 }),
      rect({ left: 800, top: 100, width: 220, height: 80, fill: GREEN, rx: 40 }),
      textbox({
        text: "NUEVO",
        left: 800,
        top: 122,
        width: 220,
        fontSize: 28,
        fontWeight: 900,
        fill: WHITE,
        textAlign: "center",
        letterSpacing: 4,
      }),
      rect({ left: 60, top: 880, width: 960, height: 140, fill: "rgba(0,0,0,0.85)" }),
      textbox({
        text: "{{title}}",
        left: 80,
        top: 905,
        width: 920,
        fontSize: 38,
        fontWeight: 800,
        fill: WHITE,
      }),
      textbox({
        text: "{{price}}",
        left: 80,
        top: 960,
        width: 920,
        fontSize: 24,
        fontWeight: 600,
        fill: GREEN,
        fontFamily: "JetBrains Mono",
      }),
    ],
  },
  // 12
  {
    id: "testimonial",
    name: "Testimonio cliente",
    description: "Quote + estrellas + foto cliente.",
    category: "agent",
    thumbnail: "⭐",
    format: "SQUARE",
    width: 1080,
    height: 1080,
    background: "#fafafa",
    objects: [
      textbox({
        text: "★★★★★",
        left: 60,
        top: 120,
        width: 960,
        fontSize: 56,
        fontWeight: 700,
        fill: GOLD,
        textAlign: "center",
      }),
      textbox({
        text: "{{testimonial_quote}}",
        left: 90,
        top: 280,
        width: 900,
        fontSize: 36,
        fontWeight: 600,
        fill: INK,
        textAlign: "center",
        fontFamily: "Playfair Display",
      }),
      textbox({
        text: "— {{client_name}}",
        left: 90,
        top: 740,
        width: 900,
        fontSize: 24,
        fontWeight: 500,
        fill: "#525252",
        textAlign: "center",
      }),
      textbox({
        text: "{{agent_name}}  ·  Agente inmobiliario",
        left: 90,
        top: 920,
        width: 900,
        fontSize: 18,
        fontWeight: 500,
        fill: GREEN,
        textAlign: "center",
      }),
    ],
  },
  // 13
  {
    id: "facebook-cover",
    name: "FB Post · Horizontal",
    description: "Formato 1200×630 para Facebook / LinkedIn.",
    category: "sale",
    thumbnail: "🖼️",
    format: "LANDSCAPE",
    width: 1200,
    height: 630,
    background: INK,
    objects: [
      placeholderImage({ left: 0, top: 0, width: 720, height: 630 }),
      textbox({
        text: "EN VENTA",
        left: 760,
        top: 100,
        width: 400,
        fontSize: 20,
        fontWeight: 800,
        fill: GREEN,
        letterSpacing: 6,
      }),
      textbox({
        text: "{{title}}",
        left: 760,
        top: 150,
        width: 400,
        fontSize: 44,
        fontWeight: 800,
        fill: WHITE,
      }),
      textbox({
        text: "{{specs}}",
        left: 760,
        top: 320,
        width: 400,
        fontSize: 18,
        fontWeight: 500,
        fill: "#a3a3a3",
      }),
      textbox({
        text: "{{price}}",
        left: 760,
        top: 380,
        width: 400,
        fontSize: 40,
        fontWeight: 900,
        fill: GREEN,
        fontFamily: "JetBrains Mono",
      }),
      textbox({
        text: "{{agent_name}}",
        left: 760,
        top: 510,
        width: 400,
        fontSize: 18,
        fontWeight: 600,
        fill: WHITE,
      }),
      textbox({
        text: "{{agent_phone}}",
        left: 760,
        top: 540,
        width: 400,
        fontSize: 16,
        fontWeight: 400,
        fill: "#a3a3a3",
      }),
    ],
  },
  // 14
  {
    id: "story-open-house",
    name: "Story · Open House",
    description: "Story vertical con fecha gigante.",
    category: "open-house",
    thumbnail: "🏠",
    format: "STORY",
    width: 1080,
    height: 1920,
    background: GREEN,
    objects: [
      textbox({
        text: "OPEN HOUSE",
        left: 60,
        top: 200,
        width: 960,
        fontSize: 48,
        fontWeight: 800,
        fill: WHITE,
        textAlign: "center",
        letterSpacing: 8,
      }),
      textbox({
        text: "{{open_house_date}}",
        left: 60,
        top: 320,
        width: 960,
        fontSize: 180,
        fontWeight: 900,
        fill: WHITE,
        textAlign: "center",
      }),
      placeholderImage({ left: 90, top: 800, width: 900, height: 700 }),
      textbox({
        text: "{{title}}",
        left: 60,
        top: 1560,
        width: 960,
        fontSize: 44,
        fontWeight: 800,
        fill: WHITE,
        textAlign: "center",
      }),
      textbox({
        text: "{{location}}  ·  RSVP {{agent_phone}}",
        left: 60,
        top: 1700,
        width: 960,
        fontSize: 22,
        fontWeight: 500,
        fill: WHITE,
        textAlign: "center",
      }),
    ],
  },
  // 15
  {
    id: "blank",
    name: "En blanco",
    description: "Lienzo limpio para empezar desde cero.",
    category: "sale",
    thumbnail: "✨",
    format: "SQUARE",
    width: 1080,
    height: 1080,
    background: WHITE,
    objects: [],
  },
];
